# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SerendipitySpin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SerendipitySpin
  pod 'LookinServer', :configurations => ['Debug']
  pod 'Firebase/Messaging'
  pod 'AppsFlyerFramework'
  pod 'FBSDKCoreKit', '17.4.0'
  pod 'Adjust'
end
